### ISSUE TITLE
Problems with graphics: flickering screen

### ISSUE THREAD

**Issue by echo2modules** [utz82/bintracker#5] opened 2017-10-04 20:41 UTC
I have problems with graphics. I don't know if this is allegro5 problem.
For some reason, when I open the tracker, the objects on the screen are constantly flickering. When I write something in the pattern, the note disappears and appears again. If I delete something from the pattern, it reappears and disappears again, although there's nothing there anymore, as if some old buffer is being displayed. I can't use the tracker because of that.
I have no idea what's happening and how to fix it.
This is how it looks like:
ok
![deepinscreenshot_bintracker_20171004221250](https://user-images.githubusercontent.com/31810100/31194921-4442504a-a951-11e7-956b-98858b94153d.png)
but then it flickers like this
![deepinscreenshot_bintracker_20171004221304](https://user-images.githubusercontent.com/31810100/31194925-46ff11d8-a951-11e7-8378-44056558bc33.png)
and then it repeats.
I'm using manjaro linux and has installed allegro5 from AUR (allegro5-git)

**Comment by utz82** [comment] 2017-10-05 09:42
Yes, this is most likely an Allegro5 problem, but nevertheless bintracker should have a work-around for this.

Ok, I tweaked the rendering loop a bit. Could you pull the latest version from the repo and see if anything changed for you? It will probably not solve the problem, but there should be some impact. For now I just want to see if I'm on the right track (because I cannot reproduce this problem on my own machine, so I need your help).

**Comment by echo2modules** [comment] 2017-10-05 19:42
Okay, now the screen doesn't flicker, but I can't interact with patterns. I can only open file opening menu and save the track but I can't edit anything nor play any track. When I open a track, it shows pattern contents like in normal state, but yet I can't change anything.
I think manual installation of allegro5 could solve the problem, but i'll keep AUR version so you can fix the playback problem.

**Comment by utz82** [comment] 2017-10-06 08:28
Alright, attempted another tweak. Please pull and test again. 
If this doesn't help, another idea would be to experiment with the default FPS parameter in gui.h:86, changing it to something like (1.0f / 30.0f).

**Comment by echo2modules** [comment] 2017-10-06 16:26
Same thing.
![deepinscreenshot_bintracker_20171006192126](https://user-images.githubusercontent.com/31810100/31287933-ac45f216-aacb-11e7-8316-6e3e5bef1d41.png)
![deepinscreenshot_bintracker_20171006192151](https://user-images.githubusercontent.com/31810100/31287934-ad55d1da-aacb-11e7-9a2e-d6004472e1f9.png)
With FPS 1.0f/30.0f it just flickers more frequently.

**Comment by utz82** [comment] 2017-10-07 09:45
Hmm, that's too bad. Ok, time to pull out some bigger guns, it seems.
In the meantime, could you post some info for me, please?
1) Allegro version
2) output of `glxinfo | grep OpenGL`

**Comment by echo2modules** [comment] 2017-10-07 23:39
I'm not sure about Allegro version, but it should be as follows: 
5.1.11.553.gca5dfea56-1

2.
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 17.2.1
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by utz82** [comment] 2017-10-09 13:24
Thanks! Ok, this is a pretty old version of Allegro. I know Ubuntu LTS ships an even older one but ultimately I'm not sure I want to support those because there will be many more bugs and incompatibilities related to them. (In hindsight I'm not even sure using Allegro was such a great choice in the first place, but well, we're kind of stuck with it now.)

Anyway, could you try to add the following code in gui.cpp:25
`al_set_new_display_option(ALLEGRO_SINGLE_BUFFER, 1, ALLEGRO_SUGGEST);`

If it doesn't solve the problem, please remove it again, then add the following in gui.cpp:195 (just before the end of the function)
```
cout << "SINGLE_BUFFER: " << al_get_display_option(mainDisplay, ALLEGRO_SINGLE_BUFFER)
       << ", SWAP_METHOD: " << al_get_display_option(mainDisplay, ALLEGRO_SWAP_METHOD) << endl;
```
and tell me the console output when running bintracker.

**Comment by farvardin** [comment] 2017-10-10 09:39
On my computer with the video problem I have this:

> OpenGL vendor string: X.Org
OpenGL renderer string: AMD BONAIRE (DRM 2.43.0 / 4.4.0-62-lowlatency, LLVM 4.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.0-rc1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.0-rc1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.0-rc1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:


I've tried you fix line 25, so I have this in the code instead:

`mainDisplay = al_create_display(settings.xres, settings.yres);
	al_set_new_display_option(ALLEGRO_SINGLE_BUFFER, 1, ALLEGRO_SUGGEST);
	if (!mainDisplay) throw (string("Failed to create window."));`

It's the same flickering problem, just the patterns look different. When I click in the pattern renaming field, the flickering stops. And start again once I leave it.

I've also added your "cout" code in the Main_Window::~Main_Window() function (at the end), but I have no output in console.

**Comment by utz82** [comment] 2017-10-10 10:02
Thanks! With this info we can be pretty sure that this is neither an OpenGL nor a graphics card related issues.

The fix for line 25 should be _before_ the `mainDisplay = al_create_display(settings.xres, settings.yres);`, sorry for not being clear about that.

Also I gave the wrong line number for the cout, it should be at the end of the constructor (so, line 191). Still odd that it won't output anything in your case.

Btw farvardin, what's the Allegro version on this machine?

**Comment by farvardin** [comment] 2017-10-10 10:07
Great, it works now, no flickering at all!
And the output is: SINGLE_BUFFER: 1, SWAP_METHOD: 0
thank you!

edit: It's liballegro5.2.3, I see it was compiled from source and installed with checkinstall

**Comment by utz82** [comment] 2017-10-10 12:05
So this problem is not related to an old version of liballegro, after all! Who'd have thought.
Anyway, I've committed some changes... with that, you can now add the following line to your settings.ini:
`SIMPLEGFXBUFFER=false`
which sets ALLEGRO_SINGLE_BUFFER = 1. It's not ideal because this type of rendering is very slow, but as mentioned, this is most likely an Allegro bug, so the proper fix must come from their side.

nonepetrovich, does this solve the problem for you as well?

**Comment by echo2modules** [comment] 2017-10-12 16:48
I see, you've already added the "al_set_new_display_option(ALLEGRO_SINGLE_BUFFER, 1, ALLEGRO_SUGGEST);" code in master. 
I've changed SIMPLEGFXBUFFER to true, and now it seems to work well! Thank you!
Now it's not flickering, everything works fine.

**Comment by utz82** [comment] 2017-10-12 22:07
Alright, so I'll consider this case closed. Thanks again for your help!

**Closed as completed by utz82** 2017-10-12 22:07 UTC
Labels: bug
